"use client";

import React, { useState } from 'react';
import { ShieldAlert, Heart, Info, User, Calendar, Stethoscope, Download, Loader2 } from 'lucide-react';
import Image from 'next/image';
import { exportDigitalIntakePdf } from '@/lib/pdf/digitalIntakePdf';

type IntakeData = {
  parentName: string;
  childName: string;
  age: string | number;
  medicalNotes: string;
  ageCare: string;
  hiddenAllergens: string;
  timestamp: string;
};

interface LeadDocProps {
  data: IntakeData | null;
  compact?: boolean;
}

export function DigitalIntakeDoc({ data, compact = false }: LeadDocProps) {
  const [isExporting, setIsExporting] = useState(false);
  const hasData = Boolean(data);
  const intakeIdLabel = data ? `ID: ${data.timestamp.split('T')[0]}-${data.childName.toLowerCase().slice(0, 3)}` : 'ID: pending';
  const ageLabel = data ? `${data.age} Years Old` : 'Pending';
  const medicalSummary = !data
    ? 'No intake data has been submitted yet. Medical notes and allergy flags will appear here once the intake is generated.'
    : data.medicalNotes === 'None'
      ? 'No immediate medical concerns reported.'
      : data.medicalNotes;
  const developmentalSummary = data
    ? `“${data.ageCare}”`
    : 'A developmental summary will appear here after the family intake has been captured.';
  const dateLabel = data ? new Date(data.timestamp).toLocaleDateString() : 'Loading';

  const handleExportPdf = async () => {
    if (!data) {
      return;
    }

    try {
      setIsExporting(true);
      await exportDigitalIntakePdf(data);
    } catch (error) {
      console.error('Failed to export intake PDF:', error);
      window.alert('The PDF could not be generated. Please try again.');
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className={`${compact ? 'flex h-full flex-col' : 'mt-8'} animate-in fade-in slide-in-from-bottom-4 duration-700`}>
      <div className="flex h-full flex-col overflow-hidden rounded-[2.5rem] border border-[#e5e0d8] bg-white shadow-[0_32px_80px_rgba(58,54,45,0.06)] backdrop-blur-sm">
        {/* Document Header */}
        <div className={`bg-[#1d3b36] text-white relative overflow-hidden ${compact ? 'p-5 md:p-6' : 'p-8 md:p-10'}`}>
          <div className="absolute top-0 right-0 w-64 h-64 bg-white/5 rounded-full -mr-32 -mt-32 blur-3xl"></div>
          
          <div className={`relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center ${compact ? 'gap-4' : 'gap-6'}`}>
            <div className="flex items-center gap-4">
              <div className={`bg-white/10 backdrop-blur-md border border-white/10 ${compact ? 'p-2.5 rounded-xl' : 'p-3 rounded-2xl'}`}>
                <Image src="/fawn-deer.svg" alt="" width={compact ? 28 : 40} height={compact ? 28 : 40} className="invert brightness-0" />
              </div>
              <div>
                <h3 className={`${compact ? 'text-xl' : 'text-2xl'} font-bold tracking-tight`}>Sunshine Daycare</h3>
                <p className={`${compact ? 'text-xs tracking-[0.22em]' : 'text-sm tracking-widest'} text-teal-100/70 font-medium uppercase mt-1`}>Digital Intake Summary</p>
              </div>
            </div>
            
            <div className="flex flex-col items-start md:items-end">
              <span className={`${compact ? 'px-3 py-1 text-[11px]' : 'px-4 py-1.5 text-xs'} bg-white/10 rounded-full font-semibold uppercase tracking-wider backdrop-blur-sm border border-white/10`}>
                {hasData ? 'Generated by Fawn AI' : 'Awaiting Intake Data'}
              </span>
              <p className={`${compact ? 'mt-1.5 text-[11px]' : 'mt-2 text-xs'} text-teal-100/50 font-mono lowercase`}>
                {intakeIdLabel}
              </p>
            </div>
          </div>
        </div>

        <div className={`grid flex-1 ${compact ? 'gap-6 p-5 md:p-6' : 'gap-12 p-8 md:p-12 lg:p-16'}`}>
          {/* Section 1: Basic Info */}
          <section>
            <div className={`flex items-center gap-3 border-b border-gray-100 ${compact ? 'mb-4 pb-3' : 'mb-6 pb-4'}`}>
              <User className="text-daycare-teal" size={compact ? 18 : 20} />
              <h4 className={`${compact ? 'text-base' : 'text-lg'} font-bold text-gray-900 uppercase tracking-tight`}>Family Profile</h4>
            </div>
            <div className={`grid grid-cols-1 md:grid-cols-3 ${compact ? 'gap-4' : 'gap-8'}`}>
              <div className="space-y-1">
                <p className="text-xs font-bold text-gray-400 uppercase tracking-widest">Child Name</p>
                <p className={`${compact ? 'text-lg' : 'text-xl'} font-semibold text-gray-900`}>{data?.childName ?? 'Waiting for submission'}</p>
              </div>
              <div className="space-y-1">
                <p className="text-xs font-bold text-gray-400 uppercase tracking-widest">Age Group</p>
                <p className={`${compact ? 'text-lg' : 'text-xl'} font-semibold text-gray-900`}>{ageLabel}</p>
              </div>
              <div className="space-y-1">
                <p className="text-xs font-bold text-gray-400 uppercase tracking-widest">Parent / Guardian</p>
                <p className={`${compact ? 'text-lg' : 'text-xl'} font-semibold text-gray-900`}>{data?.parentName ?? 'Waiting for submission'}</p>
              </div>
            </div>
          </section>

          {/* Section 2: Care & Safety */}
          <div className={`grid grid-cols-1 ${compact ? 'gap-5' : 'lg:grid-cols-2 gap-10'}`}>
            {/* Medical Notes */}
            <section className={`bg-rose-50/50 border border-rose-100/50 ${compact ? 'rounded-2xl p-5' : 'rounded-3xl p-8'}`}>
              <div className={`flex items-center gap-3 ${compact ? 'mb-4' : 'mb-6'}`}>
                <div className={`bg-rose-100 text-rose-600 ${compact ? 'p-2 rounded-lg' : 'p-2 rounded-xl'}`}>
                  <Stethoscope size={compact ? 18 : 20} />
                </div>
                <h4 className={`${compact ? 'text-base' : 'text-lg'} font-bold text-gray-900 tracking-tight`}>Medical & Allergies</h4>
              </div>
              <div className={`${compact ? 'space-y-3' : 'space-y-4'}`}>
                <p className={`text-gray-700 font-medium ${compact ? 'text-sm leading-6' : 'leading-relaxed'}`}>
                  {medicalSummary}
                </p>
                {data && data.medicalNotes !== 'None' && (
                  <div className={`flex items-start gap-3 bg-white/60 border border-rose-100 ${compact ? 'rounded-xl p-3' : 'rounded-2xl p-4'}`}>
                    <ShieldAlert className="text-rose-500 shrink-0 mt-0.5" size={compact ? 16 : 18} />
                    <div className={`${compact ? 'text-xs' : 'text-sm'}`}>
                      <p className="font-bold text-rose-900 mb-1 leading-none">AI Safety Insight: Hidden Allergens</p>
                      <p className="text-rose-800/80 leading-relaxed italic">{data.hiddenAllergens}</p>
                    </div>
                  </div>
                )}
              </div>
            </section>

            {/* Age Care */}
            <section className={`bg-teal-50/50 border border-teal-100/50 ${compact ? 'rounded-2xl p-5' : 'rounded-3xl p-8'}`}>
              <div className={`flex items-center gap-3 ${compact ? 'mb-4' : 'mb-6'}`}>
                <div className={`bg-teal-100 text-daycare-teal ${compact ? 'p-2 rounded-lg' : 'p-2 rounded-xl'}`}>
                  <Heart size={compact ? 18 : 20} />
                </div>
                <h4 className={`${compact ? 'text-base' : 'text-lg'} font-bold text-gray-900 tracking-tight`}>Developmental Focus</h4>
              </div>
              <p className={`text-gray-700 leading-relaxed italic ${compact ? 'text-base' : 'text-lg'}`}>
                {developmentalSummary}
              </p>
            </section>
          </div>

          {/* Footer Info */}
          <div className={`flex items-center justify-between border-t border-gray-100 ${compact ? 'pt-5' : 'pt-8'}`}>
            <div className="flex items-center gap-2 text-gray-400">
              <Calendar size={14} />
              <span className="text-xs font-medium uppercase tracking-[0.2em]">
                {dateLabel}
              </span>
            </div>
            <button
              type="button"
              onClick={handleExportPdf}
              disabled={!hasData || isExporting}
              className="flex items-center gap-2 px-4 py-2 bg-gray-900 text-white rounded-xl text-xs font-bold uppercase tracking-widest hover:bg-black transition-colors disabled:cursor-not-allowed disabled:bg-gray-500"
            >
              {isExporting ? <Loader2 size={14} className="animate-spin" /> : <Download size={14} />}
              {!hasData ? 'PDF Unavailable' : isExporting ? 'Generating...' : 'Export PDF'}
            </button>
          </div>

          {compact && (
            <div className="inline-flex items-center justify-center gap-2 rounded-lg border border-yellow-200 bg-yellow-100 px-4 py-2 text-[11px] font-bold uppercase tracking-[0.18em] text-yellow-800 shadow-sm">
              <Info size={13} />
              {hasData
                ? 'AI-generated summary for internal review.'
                : 'Visible now, export unlocks once intake data is available.'}
            </div>
          )}
        </div>
      </div>

      {!compact && (
        <div className="mt-6 flex justify-center">
        <div className="inline-flex items-center gap-2 px-4 py-2 bg-yellow-100 text-yellow-800 rounded-lg text-xs font-bold uppercase tracking-widest border border-yellow-200 shadow-sm">
          <Info size={14} />
          {hasData
            ? 'Note: This document is an AI-generated summary for internal review.'
            : 'Note: Intake summary is visible now, but export stays disabled until data is available.'}
        </div>
        </div>
      )}
    </div>
  );
}
