"use client";

import React, { useRef } from 'react';
import { FileText, ShieldAlert, Heart, Info, User, Calendar, Stethoscope, Download } from 'lucide-react';
import Image from 'next/image';
import { useReactToPrint } from 'react-to-print';

interface LeadDocProps {
  data: {
    parentName: string;
    childName: string;
    age: string | number;
    medicalNotes: string;
    ageCare: string;
    hiddenAllergens: string;
    timestamp: string;
  };
}

export function DigitalIntakeDoc({ data }: LeadDocProps) {
  const contentRef = useRef<HTMLDivElement>(null);
  
  const handlePrint = useReactToPrint({
    contentRef,
    documentTitle: `Sunshine_Daycare_Intake_${data.childName.replace(/\s+/g, '_')}`,
  });

  return (
    <div className="mt-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
      <style jsx global>{`
        @media print {
          @page {
            size: auto;
            margin: 15mm;
          }
          body {
            background-color: white !important;
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          .no-print {
            display: none !important;
          }
          .print-container {
            margin: 0 !important;
            padding: 0 !important;
            box-shadow: none !important;
            border: none !important;
            width: 100% !important;
            max-width: 100% !important;
          }
          /* Ensure backgrounds are captured */
          .bg-stone-50 { background-color: #f9f8f6 !important; }
          .bg-[#1d3b36] { background-color: #1d3b36 !important; }
          .bg-rose-50\/50 { background-color: rgba(255, 241, 242, 0.5) !important; }
          .bg-teal-50\/50 { background-color: rgba(240, 253, 250, 0.5) !important; }
          .bg-white\/10 { background-color: rgba(255, 255, 255, 0.1) !important; }
        }
      `}</style>

      <div 
        ref={contentRef}
        className="print-container overflow-hidden rounded-[2.5rem] border border-[#e5e0d8] bg-white shadow-[0_32px_80px_rgba(58,54,45,0.06)] backdrop-blur-sm"
      >
        {/* Document Header */}
        <div className="bg-[#1d3b36] p-8 md:p-10 text-white relative overflow-hidden">
          <div className="absolute top-0 right-0 w-64 h-64 bg-white/5 rounded-full -mr-32 -mt-32 blur-3xl"></div>
          
          <div className="relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
            <div className="flex items-center gap-4">
              <div className="bg-white/10 p-3 rounded-2xl backdrop-blur-md border border-white/10">
                <Image src="/fawn-deer.svg" alt="" width={40} height={40} className="invert brightness-0" />
              </div>
              <div>
                <h3 className="text-2xl font-bold tracking-tight">Sunshine Daycare</h3>
                <p className="text-teal-100/70 text-sm font-medium uppercase tracking-widest mt-1">Digital Intake Summary</p>
              </div>
            </div>
            
            <div className="flex flex-col items-start md:items-end">
              <span className="px-4 py-1.5 bg-white/10 rounded-full text-xs font-semibold uppercase tracking-wider backdrop-blur-sm border border-white/10">
                Generated by Fawn AI
              </span>
              <p className="mt-2 text-teal-100/50 text-xs font-mono lowercase">
                ID: {data.timestamp.split('T')[0]}-{data.childName.toLowerCase().slice(0,3)}
              </p>
            </div>
          </div>
        </div>

        <div className="p-8 md:p-12 lg:p-16 grid gap-12">
          {/* Section 1: Basic Info */}
          <section>
            <div className="flex items-center gap-3 mb-6 border-b border-gray-100 pb-4">
              <User className="text-daycare-teal" size={20} />
              <h4 className="text-lg font-bold text-gray-900 uppercase tracking-tight">Family Profile</h4>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              <div className="space-y-1">
                <p className="text-xs font-bold text-gray-400 uppercase tracking-widest">Child Name</p>
                <p className="text-xl font-semibold text-gray-900">{data.childName}</p>
              </div>
              <div className="space-y-1">
                <p className="text-xs font-bold text-gray-400 uppercase tracking-widest">Age Group</p>
                <p className="text-xl font-semibold text-gray-900">{data.age} Years Old</p>
              </div>
              <div className="space-y-1">
                <p className="text-xs font-bold text-gray-400 uppercase tracking-widest">Parent / Guardian</p>
                <p className="text-xl font-semibold text-gray-900">{data.parentName}</p>
              </div>
            </div>
          </section>

          {/* Section 2: Care & Safety */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
            {/* Medical Notes */}
            <section className="bg-rose-50/50 rounded-3xl p-8 border border-rose-100/50">
              <div className="flex items-center gap-3 mb-6">
                <div className="bg-rose-100 p-2 rounded-xl text-rose-600">
                  <Stethoscope size={20} />
                </div>
                <h4 className="text-lg font-bold text-gray-900 tracking-tight">Medical & Allergies</h4>
              </div>
              <div className="space-y-4">
                <p className="text-gray-700 leading-relaxed font-medium">
                  {data.medicalNotes === 'None' ? 'No immediate medical concerns reported.' : data.medicalNotes}
                </p>
                {data.medicalNotes !== 'None' && (
                  <div className="flex items-start gap-3 bg-white/60 rounded-2xl p-4 border border-rose-100">
                    <ShieldAlert className="text-rose-500 shrink-0 mt-0.5" size={18} />
                    <div className="text-sm">
                      <p className="font-bold text-rose-900 mb-1 leading-none">AI Safety Insight: Hidden Allergens</p>
                      <p className="text-rose-800/80 leading-relaxed italic">{data.hiddenAllergens}</p>
                    </div>
                  </div>
                )}
              </div>
            </section>

            {/* Age Care */}
            <section className="bg-teal-50/50 rounded-3xl p-8 border border-teal-100/50">
              <div className="flex items-center gap-3 mb-6">
                <div className="bg-teal-100 p-2 rounded-xl text-daycare-teal">
                  <Heart size={20} />
                </div>
                <h4 className="text-lg font-bold text-gray-900 tracking-tight">Developmental Focus</h4>
              </div>
              <p className="text-gray-700 leading-relaxed italic text-lg">
                &ldquo;{data.ageCare}&rdquo;
              </p>
            </section>
          </div>

          {/* Footer Info */}
          <div className="flex items-center justify-between pt-8 border-t border-gray-100">
            <div className="flex items-center gap-2 text-gray-400">
              <Calendar size={14} />
              <span className="text-xs font-medium uppercase tracking-[0.2em]">{new Date(data.timestamp).toLocaleDateString()}</span>
            </div>
            <button 
              onClick={() => handlePrint()}
              className="no-print flex items-center gap-2 px-4 py-2 bg-gray-900 text-white rounded-xl text-xs font-bold uppercase tracking-widest hover:bg-black transition-colors"
            >
              <Download size={14} />
              Export PDF
            </button>
          </div>
        </div>
      </div>

      <div className="no-print mt-6 flex justify-center">
        <div className="inline-flex items-center gap-2 px-4 py-2 bg-yellow-100 text-yellow-800 rounded-lg text-xs font-bold uppercase tracking-widest border border-yellow-200 shadow-sm">
          <Info size={14} />
          Note: This document is an AI-generated summary for internal review.
        </div>
      </div>
    </div>
  );
}
